# -*- coding: utf-8 -*-
"""stack_implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1so7Wq8edentSyxhS4Kd2qZIO2gZXQvqd
"""

stack=[]
def push():
  element= input("enter an element: ")
  stack.append(element)
  print(stack)

def pop_element():
  if len(stack)==0:
    print("stack is empty")
  else:
    e= stack.pop()
    print("removed stack element: ", e)
    print(stack)

while True:
  print("select the op: 1. push 2. pop 3. quit")
  choice = int(input())
  if choice==1:
    push()
  elif choice==2:
    pop_element()
  else:
    print("eneter correct operation")